version: '3.4'

networks:
  network:

services:
  nginx:
    image: nginx:latest
    container_name: server-demo
    restart: unless-stopped
    ports:
  # app port
      - "8080:8080" # spv

   # mfe port
      # - "8200:8200" # auth 

    volumes:
      - ./etos:/usr/share/nginx/html/etos
      - ./ojiepermana:/usr/share/nginx/html/ojiepermana
      - ./nginx:/etc/nginx/conf.d
    networks:
      - network